[package]
name = "custard"
version = "0.1.0"
edition = "2021"
authors = ["veritius <veritiusgaming@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "A text adventure game engine."

[dependencies]
termion = "4"
smallvec = "1"
smartstring = "1"